version: '3' 

services:

db:
  image: mysql:latest
   environment:
    MYSQL_ROOT_PASSWORD: testpass
    MYSQL_DATABASE: test_db
    MYSQL_USER: test_user
    MYSQL_PASSWORD: test_user_pass
#  ports:
#    - "3306:3306"
   volumes:
     - ./db:/docker-entrypoint-initdb.d

web:
  image: tomcat:latest
   environment:
    JDBC_URL: jdbc:mysql://db:3306/test_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
    JDBC_USER: test_user
    JDBC_PASS: test_user_db_pass
   ports:
   - "80:8080"
   volumes:
   - ./tomcat/webapps:/usr/local/tomcat/webapps
   links:
    - db
