db:
  image: mysql:latest
  volumes:
     - ./db:/docker-entrypoint-initdb.d
  environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_user_pass

web:
  image: tomcat:latest
  ports:
      - "8056:8080"
  volumes:
      - ./target:/usr/local/tomcat/webapps
  environment:
      JDBC_URL: jdbc:mysql://db:3306/test_db?connectTimeout=0&amp;socketTimeout=0&amp;autoReconnect=true
      JDBC_USER: test_user
      JDBC_PASS: test_user_db_pass
  links:
      - db
